## Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np

In [18]:
def vander_matrix(ip, N, increasing = False):
    if not increasing:
        op_mat = np.array([x**(N-1-i) for x in ip for i in range(N)]).reshape(ip.size,N)
    elif increasing:
        op_mat = np.array([x**i for x in ip for i in range(N)]).reshape(ip.size, N)
    return op_mat

In [22]:
ip = np.array([1,2,3,4,5])

van_mat_inc = vander_matrix(ip, 5, True)
van_mat_dec = vander_matrix(ip, 5, False)

In [34]:
print(ip)
print("Vander Matrix in increasing order :")
print(van_mat_inc)
print("Vander Matrix in descending order :")
print(van_mat_dec)

[1 2 3 4 5]
Vander Matrix in increasing order :
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
Vander Matrix in descending order :
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


## Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
## the given sequence is defined as follows:
## The moving average sequence has n-k+1 elements as shown below.
## The moving averages with k=4 of a ten-value sequence (n=10) is shown below
## i 1 2 3 4 5 6 7 8 9 10
## ===== == == == == == == == == == ==
## Input 10 20 30 40 50 60 70 80 90 100
## y1 25 = (10+20+30+40)/4
## y2 35 = (20+30+40+50)/4
## y3 45 = (30+40+50+60)/4
## y4 55 = (40+50+60+70)/4
## y5 65 = (50+60+70+80)/4
## y6 75 = (60+70+80+90)/4
## y7 85 = (70+80+90+100)/4
## Thus, the moving average sequence has n-k+1=10-4+1=7 values.
## Question: Write a function to find moving average in an array over a window:
## Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [37]:
def moving_average(a,n = 3):
    x = np.cumsum(a, dtype = float)
    x[n:] = x[n:] - x[:-n]
    return x[n-1:]/n

In [38]:
x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(x, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
